services:
  app:
    build: .
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/University_portal
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-broker:9092
    networks:
      - kafka-network

  mysql:
    image: mysql:8.0.43
    environment:
      MYSQL_ROOT_PASSWORD: ${ADMIN_PASSWORD}
      MYSQL_DATABASE: University_portal
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${ADMIN_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - kafka-network

volumes:
  mysql_data:

networks:
  kafka-network:
    external: true
    name: kafka-network



    